### PR TITLE
fix install partly

### PR DESCRIPTION
**Pull request by hoelzer**
Just some minor fixes, but still I had issues w/ 

```
jupyter labextension install jupyterlab_3dmol
```

apparently, due to missing Node.js and npm (siehe auch https://github.com/ncbi/icn3d/issues/76)

Tried 

```
conda install -c conda-forge nodejs
```

and then was able also to run

```
jupyter labextension install jupyterlab_3dmol
```

but still when using

```
jupyter notebook example.ipynb
```

the notebook starts but still shows

Screenshot 2022-08-17 at 08 41 38

### CODE REVIEW

**Comment by phiweger** [comment]
install steps also documented here https://pypi.org/project/icn3dpy/

**Comment by phiweger** [comment]
also maybe reload conda env, restart browser and rerun notebook

**Comment by hoelzer** [comment]
> also maybe reload conda env, restart browser and rerun notebook

tried that on my mac, also does not work and shows only the error mssg instead of protein figures in the notebook. 

Then tried to install everything on Linux laptop but building the conda env (including now also `nodejs`) fails already due to conflicts. Then tried mamba instead of conda. 

```
mamba env create -n $ENV_NAME --file install/requirements.yml 
```

that resulted in

Encountered problems while solving.
Problem: nothing provides boost 1.57.0 needed by dssp-2.2.1-0

Adding boost explicitly results in the next missing package...

Not sure what to do here. So I tried to figure out which package causes the conflict. It seems to be `dssp` from this `salilab` channel. Without the `dssp` package the env installs on my Linux. My workaround was:

```
# install the env w/o dssp
mamba env create -n $ENV_NAME --file install/requirements.yml
conda activate faltwerk
mamba install -c salilab dssp
```

but this runs into the next conflicts.... -.-

Not sure why on Mac it was able to resolve the env but not on Linux. But maybe that's also the reason why in the end it did not completely work on my Mac.

How about a container? :D

**Comment by phiweger** [comment]
@hoelzer can you try to install https://pypi.org/project/icn3dpy/ in some separate repo? just to start on the rendering in a notebook issue.

**Comment by phiweger** [comment]
Maybe one needs to "rebuild" jupyter, see https://github.com/3dmol/jupyterlab_3Dmol#development

Maybe relevant: https://github.com/3dmol/jupyterlab_3Dmol/issues/2

@hoelzer how did you install node.js? what versions of node and npm did this install?

**Comment by phiweger** [comment]
> I've installed the latest version of JupyterLab (0.34.6) and the install of the jupyterlab_3dmol extension works. I think the problem was that I have Node v10.4.1 which was not compatible with earlier versions of JupyterLab (https://github.com/jupyterlab/jupyterlab/pull/5121). -- source: https://github.com/jupyterlab/jupyterlab/issues/5225

FFS

**Comment by hoelzer** [comment]
> > I've installed the latest version of JupyterLab (0.34.6) and the install of the jupyterlab_3dmol extension works. I think the problem was that I have Node v10.4.1 which was not compatible with earlier versions of JupyterLab ([jupyterlab/jupyterlab#5121](https://github.com/jupyterlab/jupyterlab/pull/5121)). -- source: [jupyterlab/jupyterlab#5225](https://github.com/jupyterlab/jupyterlab/issues/5225)
> 
> FFS

on the mac I have Node.js v18.7.0 and installed via conda. jupyerlab is v3.4.5 apparently (`jupyter --version`)

**Comment by hoelzer** [comment]
On Linux:

```bash
conda create -n faltwerk
conda activate faltwerk
mamba install -c salilab python jupyter notebook foldseek hmmer dssp nodejs biopython
```

finally worked to install the first dependencies. Python was installed in v3.10.4 and foldseek in v1.3c64211 however... likely that's problematic bc/ the foldseek version is too old... 

I also tried then

```bash
mamba install -c salilab python jupyter notebook foldseek=3.915ef7d hmmer dssp nodejs biopython
```

which ends in conflicts. 

So I continued w/ the env w/ the older foldseek version and run:

```bash
pip install -r install/more_requirements.txt
jupyter labextension install jupyterlab_3dmol
# and again the command is not found -.- although nodejs should have been installed via mamba this time. Thus, I installed jupyterlab (again) via pip and then was able to also run the labextension command:
pip install jupyterlab
jupyter labextension install jupyterlab_3dmol
pip install -e .
conda deactivate
conda clean -a
conda activate faltwerk
```

And then started the example notebook and still

> You appear to be running in JupyterLab (or JavaScript failed to load for some other reason). You need to install the 3dmol extension: jupyter labextension install jupyterlab_3dmol

arghhh o-O

**Comment by phiweger** [comment]
@hoelzer can you try to install just `conda install` python and node, then 

```
pip install jupyter notebook biopython
jupyter labextension install jupyterlab_3dmol
# now the pip packages
``` 

And then try to load a minimal example (remaining conda packages not necessary).

```
from faltwerk.models import Fold
from faltwerk.vis import Layout

# take the file I sent you in the chat
fp = '...'
model = Fold(fp)
Layout(model).geom_ribbon().render().show()
```

Does that work?

**Comment by phiweger** [comment]
Hm. Read this:

https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#installing-extensions

> A JupyterLab extension contains JavaScript that is installed into Jupyterlab and run in the browser. An extension contains one or more plugins that extend JupyterLab. There are two types of JupyterLab extensions: a source extension (which requires a rebuild of JupyterLab when installed), and a prebuilt extension (which does not require a rebuild of JupyterLab). Rebuilding JupyterLab requires Node.js to be installed.

rebuild?

> Installing a source extension requires Node.js and a JupyterLab rebuild to activate. See Installing Node.js and Managing Extensions with jupyter labextension.

https://jupyterlab.readthedocs.io/en/stable/user/extensions.html#installing-and-uninstalling-source-extensions

`jupyter lab build`

Maybe rebuilding is important. I don't really remember doing any of this, but then again, maybe I did ...

In theory, this rebuilding thing should not be necessary, only for the development version:

https://github.com/3dmol/jupyterlab_3Dmol#development

```
npm install
npm run build
jupyter labextension link .
# To rebuild the package and the JupyterLab app:
npm run build
jupyter lab build
```

**Comment by phiweger** [comment]
superweird.

on my linux machine, this works:

```
mamba create -y -n faltwerk python=3.10 && conda activate faltwerk
pip install notebook py3Dmol biopython pandas screed
git clone https://www.github.com/phiweger/faltwerk && cd faltwerk
pip install -e .
jupyter notebook
```

... and then the above minimal program works. No node, no extension, ... browser is Firefox.

**Comment by hoelzer** [comment]
> ```
> jupyter notebook
> ```

Okay, just quickly tested this. And then the notebook seems to start w/o error and shows

image

Now run to the train ;)

**Comment by phiweger** [comment]
right, now create a new notebook using "new" and -- assuming your in the `faltwerk` github repo -- run

```
from faltwerk.models import Fold
from faltwerk.vis import Layout

fp = 'data/alphafold2/test_08df6_unrelaxed_rank_1_model_3.pdb'
model = Fold(fp)
Layout(model).geom_ribbon().render().show()
```

**Comment by phiweger** [comment]
Another path, just registering here before thought lost. On the `3Dmol.js` website clicking "Jupyter" a colab opens up. Checking versions there.

https://3dmol.csb.pitt.edu/

```
!node --version

v14.16.0

!jupyter --version

Selected Jupyter core packages...
IPython          : 7.9.0
ipykernel        : 5.3.4
ipywidgets       : 7.7.1
jupyter_client   : 6.1.12
jupyter_core     : 4.11.1
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : not installed
nbconvert        : 5.6.1
nbformat         : 5.4.0
notebook         : 5.3.1
qtconsole        : not installed
traitlets        : 5.1.1
```

Just for comparison, on my laptop and using the original `install.sh` I get <see below> which is the same as @hoelzer 

```
Selected Jupyter core packages...
IPython          : 8.4.0
ipykernel        : 6.15.1
ipywidgets       : 7.7.1
jupyter_client   : 7.3.4
jupyter_core     : 4.11.1
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : 0.6.6
nbconvert        : 6.5.3
nbformat         : 5.4.0
notebook         : 6.4.12
qtconsole        : 5.3.1
traitlets        : 5.3.0
```

not sure however if that colab version is before the `jupyter(lab?)` change https://github.com/3dmol/3Dmol.js/issues/362

**Pull request closed without merging**
